config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'main#hello'

  resources :payments
  resources :balances
  resources :collaborations
  resources :users do
    resources :presents
    resources :balances
    resources :payments
  end
  resources :presents do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/present.rb
class Present < ApplicationRecord
	has_many :collaborations
	has_many :users, through: :collaborations
  #has_one :buyer,->(collaboration) { where collaboration.is_buyer: true}, class_name: 'User'
  #has_one :buyer,->(present) { joins(users: :collaborations).where("collabrations.present_id": present.id)}, class_name: 'User'

  def buyer
    collaborations.buyer.first.user
  end

end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_action :set_present, only: [:show, :edit, :update, :destroy]

  # GET /presents
  # GET /presents.json
  def index
    @presents = Present.all
  end

  # GET /presents/1
  # GET /presents/1.json
  def show
  end

  # GET /presents/new
  def new
    @present = Present.new
  end

  # GET /presents/1/edit
  def edit
  end

  # POST /presents
  # POST /presents.json
  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.html { redirect_to @present, notice: 'Present was successfully created.' }
        format.json { render :show, status: :created, location: @present }
      else
        format.html { render :new }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presents/1
  # PATCH/PUT /presents/1.json
  def update
    respond_to do |format|
      if @present.update(present_params)
        format.html { redirect_to @present, notice: 'Present was successfully updated.' }
        format.json { render :show, status: :ok, location: @present }
      else
        format.html { render :edit }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present.destroy
    respond_to do |format|
      format.html { redirect_to presents_url, notice: 'Present was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_present
      @present = Present.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def present_params
      params.require(:present).permit(:description, :price)
    end
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/presents/_form.html.erb
<%= form_for(present) do |f| %>
  <% if present.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
      <% present.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presents/edit.html.erb
<h1>Editing Present</h1>

<%= render 'form', present: @present %>

<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>

app/views/presents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presents</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presents.each do |present| %>
      <tr>
        <td><%= present.description %></td>
        <td><%= present.price %></td>
        <td><%= link_to 'Show', present %></td>
        <td><%= link_to 'Edit', edit_present_path(present) %></td>
        <td><%= link_to 'Destroy', present, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Present', new_present_path %>

app/views/presents/new.html.erb
<h1>New Present</h1>

<%= render 'form', present: @present %>

<%= link_to 'Back', presents_path %>

app/views/presents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @present.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @present.price %>
</p>

<%= link_to 'Edit', edit_present_path(@present) %> |
<%= link_to 'Back', presents_path %>